### ISSUE TITLE
XcertProof recipe proposal

### ISSUE THREAD

**Issue by xpepermint** [0xcert/specs#6]
## Simple Summary

A recipe convention describing a proof for Xcert token.

## Abstract

The following convention is a JSON schema recipe object which describes a `Xcert proof` as a digital asset. The recipe provides the required and optional fields and represents a proof of a digital asset.

## Features

- [ ] Basic information

## Schema

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "An Xcert proof document.",
  "properties": {
    "publicDigest": {
      "$ref": "#/message-digest"
    },
    "privateDigest": {
      "$ref": "#/message-digest"
    }
  },
  "required": [
    "publicDigest",
    "privateDigest"
  ],
  "title": "XcertProof",
  "type": "object"
}
```

**Comment by leonpanjtar** [comment]
We need to add "id" property to the XcertProof Schema. Currently if you run the schema trough validator, it is not valid becouse $ref-s are not resolved.

id property serves two purpuses:
- declares a unique identifier for the schema.
- declares a base URL against which $ref URLs are resolved.

So my suggestion is to add property id and fill it with schema base URL which resolves all refs and schema definitions:
``
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "id": "https://0xcert.org/schema"
  "description": "An Xcert proof document.",
  "properties": {
    "publicDigest": {
      "$ref": "#/message-digest"
    },
    "privateDigest": {
      "$ref": "#/message-digest"
    }
  },
  "required": [
    "publicDigest",
    "privateDigest"
  ],
  "title": "XcertProof",
  "type": "object"
}
``

Example: MessageDigest would be resolved to https://0xcert.org/schema#/message-digest
