### ISSUE TITLE
DigitalAsset schema proposal

### ISSUE THREAD

**Issue by xpepermint** [0xcert/specs#8]
## Simple Summary

A convention describing a base **digital asset**.

## Abstract

The following convention is a [JSON schema](http://json-schema.org/) describing a [digital asset](https://en.wikipedia.org/wiki/Digital_asset). This is the base schema from which all other schemas are extended. It follows the [ERC721 Metadata JSON Schema](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md) proposal.

## Features

- [x] Basic asset information

## Schema

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "id": "https://specs.0xcert.org/schemas/digital-asset.json",
  "description": "A digital asset metadata.",
  "properties": {
    "description": {
      "type": "string",
      "description": "Describes the asset to which this NFT represents.",
    },
    "image": {
      "type": "string",
      "description": "A URI pointing to a resource with mime type image/* representing the asset to which this NFT represents. Consider making any images at a width between 320 and 1080 pixels and aspect ratio between 1.91:1 and 4:5 inclusive."
    },
    "name": {
      "type": "string",
      "description": "Identifies the asset to which this NFT represents.",
    }
  },
  "meta": [
    "description",
    "image",
    "name"
  ],
  "title": "DigitalAsset",
  "type": "object"
}
```

**Comment by xpepermint** [comment]
@leonpanjtar @MoMannn I think this one can be merged. Thoughts?

**Comment by leonpanjtar** [comment]
I would add "identifier" property to the main object.

**Comment by xpepermint** [comment]
The identifier is the NFT ID. That's probably why it's not included in erc721 JSON proposal at https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md.

**Comment by xpepermint** [comment]
https://github.com/0xcert/specs/pull/9

**Comment by leonpanjtar** [comment]
Test case - https://www.jsonschemavalidator.net/:

```
{
    "description": "This is a sample Digital asset definition.",
    "image": "http://via.placeholder.com/350x150",
    "name": "Test Digital Asset"
}

```
